[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    -v
    -ra
    --strict-markers
    --tb=short
    --alluredir=allure-results
    --clean-alluredir
markers =
    smoke: быстрые проверки доступности и структуры
    ui: тесты пользовательского интерфейса
    mobile: тесты адаптивности под мобильные разрешения
